# Generated by Django 5.2 on 2025-04-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profils"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(
                default=True,
                help_text="Indique si l'utilisateur doit changer son mot de passe à la prochaine connexion",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil de l'utilisateur",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="secureauth.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Adresse email unique", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de la dernière tentative échouée",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure jusqu'à laquelle le compte est verrouillé",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_attempts",
            field=models.IntegerField(
                default=0, help_text="Nombre de tentatives de connexion échouées"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(help_text="Mot de passe haché", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="pseudonym",
            field=models.CharField(
                help_text="Pseudonyme unique (min. 5 caractères, sans chiffres)",
                max_length=255,
                unique=True,
            ),
        ),
    ]
