# Generated by Django 5.2 on 2025-04-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("secureauth", "0002_alter_profile_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("style_graphique", models.CharField(max_length=255)),
                ("ambiance_visuelle", models.CharField(max_length=255)),
                ("ambiance_narrative", models.CharField(max_length=255)),
                ("mots_cles", models.CharField(max_length=255)),
                ("reference_culturelle", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureauth.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("univers_de_jeu", models.TextField()),
                ("histoire_principale", models.TextField()),
                ("personnages", models.TextField()),
                ("illustrations_conceptuelles", models.TextField()),
                ("pitch_deck", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureauth.user",
                    ),
                ),
                (
                    "game_idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameforge.gameidea",
                    ),
                ),
            ],
        ),
    ]
